# Generated by Django 5.1.7 on 2025-04-03 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('pdf', 'PDF File'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('jpg', 'JPEG Image'), ('png', 'PNG Image')], default='txt', max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
