# Generated by Django 5.1.7 on 2025-04-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
